#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
SECONDS=0
fecha=$(date +%d-%m-%Y)
cssh="ssh -4 -C -q -o StrictHostKeyChecking=no -o ConnectTimeout=3 -p 22"
suser="USUARIO"
archi="/tmp/claves.txt"
donde="/tmp"
ctar="tar -czf"
qre="qrencode -c -m 1 -s 10 -l H -d 100"
cfrom="user@mail.com"
cserver="mail.mail.com"
cport="587"
cuser="user@mail.com"
cpass="3664g5h"
cdestinos="user1@mail.com,user2@mail.com"
nssid="visita"
ips=(192.168.0.1 192.168.0.2 192.168.0.3 192.168.0.4 192.168.0.5 192.168.0.6)
correo='swaks -4 --to $cdestinos --from $cfrom --server $cserver:$cport -tls --auth LOGIN --auth-user $cuser --auth-password $cpass'

function clean_1() {
	rm -f $archi
	rm -f $donde/*.tar.gz
	rm -rf $donde/qr/
}

if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
	exit 1
fi

trap "clean_1; exit" 0 1 2 3 9 15
clear

mkdir -p $donde/qr

for i in ${ips[@]}; do
	clave=$(dd if=/dev/urandom bs=1 count=64 2>/dev/null | base64 -w 0 | tr -dc _A-Z-a-z-0-9 | cut -c 1-8)
	echo "IP: $i"
	echo "IP: $i" >> $archi
	echo "Clave: $clave"
	echo "Clave: $clave" >> $archi
	echo "=========================" >> $archi
	$qre "WIFI:T:WPA;S:$nssid;P:$clave;;" -o $donde/qr/$i.png
	$cssh $suser@$i "caps-man security set visita passphrase=$clave"
done

$ctar $donde/qr-$fecha.tar.gz $donde/qr/

echo "correo"
$correo --output $donde/clavewifi.log --header "Subject: Cambio de clave de SSID visita %DATE%" --body "Se cambiaron las claves de los SSID VISITA, se adjunta el archivo." --attach-type "text/plain" --attach-name "claves.txt" --attach @/tmp/claves.txt --attach-type "application/x-compressed-tar" --attach-name "qr-$fecha.tar.gz" --attach @/tmp/qr-$fecha.tar.gz
echo "duracion $SECONDS segundos"
echo "Finalizado."
exit 0
